server:
  port: 18090

spring:
  datasource:
    username: xio
    password: 123456
    url: jdbc:mysql://192.168.1.105:3306/xio
    driver-class-name: com.mysql.cj.jdbc.Driver

# 测试字典列表
opcconfig:
  nodes:
    - url: 'opc.tcp://192.168.1.105:49320'
      name: 'test'
      namespaceIndex: 2
      identifier: '通道 1.设备 1.test'
    - url: 'opc.tcp://192.168.1.105:49320'
      name: 'test2'
      namespaceIndex: 2
      identifier: '通道 1.设备 1.test'
